### ISSUE TITLE
[FEATURE] Caret Cursor Position After Command Execution

### ISSUE THREAD

**Issue by FelipeRearden** [StrangeGirlMurph/obsidian-wikipedia-search#7]
# Description of the Problem

Hello @StrangeGirlMurph !!!!

This FR is simple to explain. I would like to change the caret cursor position after hitting the command `Search Article`.

# Description of the Solution

The Caret Cursor position should be placed in the beginning of the **insertion** instead i of the end. 

# Additional

This FR is easier to understand after knowing my workflow.

→ I use `{extract}`  in the format field. This way, every time I have to go to the start of the content after executing the command to read 

https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/assets/85180696/0eebcd3b-cfbc-4fe5-88de-eed424474933

As you can see from the video, I insert the content from this plugin to a support note in the left side to read about the term that I search on wikipedia. This way I dont have to exit Obsidian anymore :)

---

Let me know if need more information!

Thank you very much for creating this amazing plugin :)

I wish you a fantastic day ☀️

**Comment by StrangeGirlMurph** [comment]
Hey, thank you! Happy you're enjoying the plugin!
Cool workflow :) Thanks for the FR! I see why the cursor placing is weird for your specific usecase. I think for most people the current cursor positioning is still better because the majority uses the plugin inside their documents directly. But I can definitely add a setting to make it appear at the beginning! I probably get to it this evening already. At latest it should be done by Saturday.
You too have a wonderful day. Murphy :)

**Comment by StrangeGirlMurph** [comment]
[Done](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/releases/tag/1.7.0) and ready to be installed :)

**Comment by FelipeRearden** [comment]
> [Done](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search/releases/tag/1.7.0) and ready to be installed :)

Hello @StrangeGirlMurph !!!!!

Thank you very much for the quick reply !!!!

Working PERFECT on Obsidian Mobile 1.4.3 on iPadOS 16.2

Again, thank you very much for this feature :)

I wish you a fantastic day ☀️
